name: Atualizar Configuração Padrão do Painel

on:
  push:
    branches:
      - main # Ou a sua branch principal
    paths:
      - '_data/nova_configuracao_padrao.json' # Gatilho quando este arquivo mudar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para a Action fazer commit de volta no repositório

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Pode usar uma versão LTS mais recente

      - name: Atualizar index.html  # <--- MUDANÇA AQUI (nome do passo, opcional)
        run: |
          # Ler o conteúdo do JSON de configuração
          CONFIG_JSON=$(cat _data/nova_configuracao_padrao.json)

          # Criar um script Node.js para fazer a substituição de forma mais segura
          cat << EOF > update_script.js
          const fs = require('fs');
          const path = require('path');

          const configFile = path.join('_data', 'nova_configuracao_padrao.json');
          const targetHtmlFile = 'index.html'; // <--- MUDANÇA AQUI: Alvo é index.html

          // Ler a nova configuração JSON
          let newConfigJsonString;
          try {
            newConfigJsonString = fs.readFileSync(configFile, 'utf8');
            // Validação básica do JSON
            JSON.parse(newConfigJsonString); // Se isso falhar, o JSON é inválido
          } catch (error) {
            console.error('Erro ao ler ou parsear o arquivo de configuração JSON:', error);
            process.exit(1);
          }

          // Ler o index.html
          let htmlContent;
          try {
            htmlContent = fs.readFileSync(targetHtmlFile, 'utf8');
          } catch (error) {
            console.error('Erro ao ler o arquivo index.html:', error); // <--- MUDANÇA AQUI
            process.exit(1);
          }

          // Encontrar e substituir a declaração de defaultReportGroupsConfig
          // ATENÇÃO: Esta regex é crucial e pode precisar de ajustes
          // Assumindo que a declaração da variável é a mesma em index.html
          const regex = /const defaultReportGroupsConfig\s*=\s*(\[[\s\S]*?\]);/gm;
          
          if (!regex.test(htmlContent)) {
            console.error('Não foi possível encontrar a declaração de defaultReportGroupsConfig no index.html. Verifique a regex e o arquivo.'); // <--- MUDANÇA AQUI
            process.exit(1);
          }

          const updatedHtmlContent = htmlContent.replace(
            regex,
            \`const defaultReportGroupsConfig = \${newConfigJsonString};\`
          );

          // Salvar o arquivo index.html modificado
          try {
            fs.writeFileSync(targetHtmlFile, updatedHtmlContent, 'utf8');
            console.log('index.html atualizado com sucesso.'); // <--- MUDANÇA AQUI
          } catch (error) {
            console.error('Erro ao salvar o index.html modificado:', error); // <--- MUDANÇA AQUI
            process.exit(1);
          }
          EOF

          node update_script.js

      - name: Commit e Push das alterações
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action-bot@github.com'
          git add index.html # <--- MUDANÇA AQUI: Adiciona index.html
          # Verifica se há algo para commitar
          if ! git diff --staged --quiet; then
            git commit -m "CHORE: Atualiza defaultReportGroupsConfig no index.html a partir de _data/nova_configuracao_padrao.json" # <--- MUDANÇA AQUI (mensagem do commit)
            git push
          else
            echo "Nenhuma alteração para commitar em index.html." # <--- MUDANÇA AQUI
          fi
